# Generated by Django 2.1.4 on 2019-01-31 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gallery',
            new_name='image',
        ),
    ]
