# Generated by Django 2.1.4 on 2018-12-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('package', models.CharField(default=0, max_length=50)),
                ('inDate', models.CharField(default=0, max_length=50)),
                ('outDate', models.CharField(default=0, max_length=50)),
            ],
        ),
    ]
