# Generated by Django 2.1.4 on 2018-12-27 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20181227_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='indiviuals',
            new_name='individuals',
        ),
    ]
