# Generated by Django 2.1.4 on 2019-01-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=400)),
                ('rating', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('display', models.DecimalField(decimal_places=0, default=0, max_digits=3, null=True)),
            ],
        ),
    ]
