# Generated by Django 2.1.4 on 2019-01-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='code',
            field=models.CharField(default='a', max_length=200),
        ),
    ]
